name: rest_frame
version: 0.1.1
description: Rest Framework
author: Mathias Remshardt <remshams@gmail.com>
homepage: https://github.com/remshams/dart_rest_frame
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: ">=0.10.0 <0.12.0"
  http: ">=0.11.1+1 <0.12.0"
